// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_web_secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseWebSecrets.apiKey,
    appId: FirebaseWebSecrets.appId,
    messagingSenderId: FirebaseWebSecrets.messagingSenderId,
    projectId: FirebaseWebSecrets.projectId,
    authDomain: FirebaseWebSecrets.authDomain,
    storageBucket: FirebaseWebSecrets.storageBucket,
    measurementId: FirebaseWebSecrets.measurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWrsaV2GVYHbnEJIaAgMsqAKUZ41FLyk',
    appId: '1:279082149910:android:fc4131b9070d5046b06d37',
    messagingSenderId: '279082149910',
    projectId: 'grilo-motor',
    storageBucket: 'grilo-motor.firebasestorage.app',
  );
}
